# Application Port
server: 
  port: ${PORT:8080}

# Logging properties 
logging:
  level:
    ROOT: info

# Mongo Db configuration
spring: 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
